// Canonical NLP Intent Enums for Career Intelligence Platform
export const INTENTS = {
  CAREER_DISCOVERY: 'CAREER_DISCOVERY',
  CAREER_COMPARISON: 'CAREER_COMPARISON',
  SKILL_REQUIREMENT: 'SKILL_REQUIREMENT',
  SKILL_GAP: 'SKILL_GAP',
  LEARNING_PLAN: 'LEARNING_PLAN',
  RESOURCE_SEARCH: 'RESOURCE_SEARCH',
  PROJECT_RECOMMENDATION: 'PROJECT_RECOMMENDATION',
  RESUME_ANALYSIS: 'RESUME_ANALYSIS',
  CAREER_READINESS: 'CAREER_READINESS',
  PROGRESS_UPDATE: 'PROGRESS_UPDATE',
  SKILL_ASSESSMENT: 'SKILL_ASSESSMENT',
  JOB_PREPARATION: 'JOB_PREPARATION',
  CERTIFICATION_ADVICE: 'CERTIFICATION_ADVICE',
  CAREER_ROADMAP: 'CAREER_ROADMAP',
  FOLLOW_UP_QUERY: 'FOLLOW_UP_QUERY',
  GENERAL_CAREER_QUESTION: 'GENERAL_CAREER_QUESTION'
};
